# Use root/example as user/password credentials
version: '3.1'
volumes:
  node_modules:
services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 5
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  csgo_back:
    build: ./csgo_visualizer_back/
    container_name: csgo_back
    ports:
      - 8001:8001
    environment:
      - MONGO_HOST=mongo
    volumes:
      - ./csgo_visualizer_back:/usr/src/app
    depends_on:
      mongo:
        condition: service_healthy
    healthcheck:
      test: curl --fail -s http://localhost:8001/ || exit 1
      interval: 1m30s
      timeout: 10s
      retries: 3
  csgo_front:
    build: ./csgo_visualizer_front/
    restart: always
    ports:
      - 8080:8080
    volumes:
      - ./csgo_visualizer_front:/app
      - node_modules:/app/node_modules
    depends_on:
      mongo:
        condition: service_healthy